"""add recipes.created_by

Revision ID: a306911a1b12
Revises: 3d189658e84d
Create Date: 2026-09-26 15:22:32.568468

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a306911a1b12"
down_revision: str | Sequence[str] | None = "3d189658e84d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("created_by", sa.String(length=64), nullable=True))
    op.create_foreign_key(
        op.f("fk_recipes_created_by"),
        "recipes",
        "users",
        ["created_by"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_recipes_created_by"), "recipes", type_="foreignkey")
    op.drop_column("recipes", "created_by")
    # ### end Alembic commands ###
